platform :ios, '10.0'

target 'GitClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # Networking
    pod 'Alamofire'
    pod 'AlamofireImage'

    # Reactive
    pod 'RxSwift',  '~> 4.5.0'
    pod 'RxCocoa',  '~> 4.5.0'

    # Dev tools
    pod 'R.swift',  '~> 5.0.3'
    
    # UI Libraries
    pod 'XLPagerTabStrip', '~> 9.0'

  target 'GitClientTests' do
    inherit! :search_paths
    # Unit Tests Framewoks
    pod 'Quick'
    pod 'RxNimble'
  end
end
